
services:
  l11dev-prod-nginx:
    container_name: l11dev-prod-nginx # コンテナ名を指定
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf # ここでdefault.prod.confを指定
      - /tmp:/tmp
    depends_on:
      - l11dev-prod-app
    networks:
      - l11dev_app-network

  l11dev-prod-app:
    container_name: l11dev-prod-app # コンテナ名を指定
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=l11dev-prod-mysql
      - DB_PORT=3306
      - DB_DATABASE=l11dev
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html           # コードをホストと共有
      - /src/node_modules         # node_modulesをコンテナ内で管理
      - /src/vendor               # vendorをコンテナ内で管理
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini  # カスタムPHP設定
    depends_on:
      - l11dev-prod-mysql
    networks:
      - l11dev_app-network
    # extra_hosts:
    #  - "l11dev-mysql:172.18.0.2" # 必要であれば追加

  l11dev-prod-mysql:
    container_name: l11dev-prod-mysql # コンテナ名を指定
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=l11dev
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql # データを永続化する
    networks:
      - l11dev_app-network
    
networks:
  l11dev_app-network:
    name: l11dev_app-network
    driver: bridge

volumes:
  mysql_data: {}
  

