FROM nginx:1.27

# Vim のインストール
RUN apt update && apt install -y vim

# 設定ファイルをコピー
# COPY ./default.prod.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf

# 必要なフォルダやファイルをコピー
COPY ./public /var/www/html

# ポートの公開
EXPOSE 80

